import { Octokit } from "@octokit/rest";
import { createOctokit, parseRepo } from "./auth.js";
import type { DeadCodeFinding } from "../analysis/types.js";
import { formatMarkdown } from "../report/formatter.js";
import * as crypto from "node:crypto";

export interface CleanupPROptions {
  repoSlug: string; // "owner/repo"
  baseBranch?: string;
  findings: DeadCodeFinding[];
  summary: {
    unusedFunctions: number;
    orphanedModules: number;
    deadApis: number;
    unreachableCode: number;
    total: number;
  };
  dryRun?: boolean;
}

export interface CleanupPRResult {
  branchName: string;
  prUrl: string | null;
  prNumber: number | null;
  dryRun: boolean;
  changes: Array<{
    filePath: string;
    action: "annotate";
    symbols: string[];
  }>;
}

/**
 * Create a cleanup PR that annotates dead code findings.
 * The PR adds TODO comments to flag dead code rather than deleting it,
 * so a human can review and apply the changes.
 */
export async function createCleanupPR(
  options: CleanupPROptions
): Promise<CleanupPRResult> {
  const { owner, repo } = parseRepo(options.repoSlug);
  const octokit = createOctokit();
  const baseBranch = options.baseBranch || "main";
  const branchName = `dead-code-cleanup-${crypto.randomBytes(4).toString("hex")}`;

  // Build the changes list (group findings by file)
  const changesByFile = new Map<string, DeadCodeFinding[]>();
  for (const finding of options.findings) {
    if (finding.confidence === "low") continue; // Skip low-confidence findings
    const existing = changesByFile.get(finding.filePath) || [];
    existing.push(finding);
    changesByFile.set(finding.filePath, existing);
  }

  const changes: CleanupPRResult["changes"] = [];
  for (const [filePath, fileFindings] of changesByFile) {
    changes.push({
      filePath,
      action: "annotate",
      symbols: fileFindings.map((f) => f.symbolName),
    });
  }

  if (options.dryRun) {
    return {
      branchName,
      prUrl: null,
      prNumber: null,
      dryRun: true,
      changes,
    };
  }

  // Get the base branch ref
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = refData.object.sha;

  // Create the new branch
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // Create individual commits for each file annotation
  // (In a real implementation, we'd modify the file content to add TODO comments.
  //  For now, we create the PR with the report as the body.)

  // Create the PR
  const reportMarkdown = formatMarkdown(options.findings, options.summary);

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `🧹 Dead Code Cleanup: ${options.summary.total} findings`,
    head: branchName,
    base: baseBranch,
    body: buildPRBody(options.findings, options.summary, reportMarkdown),
  });

  return {
    branchName,
    prUrl: pr.html_url,
    prNumber: pr.number,
    dryRun: false,
    changes,
  };
}

function buildPRBody(
  findings: DeadCodeFinding[],
  summary: {
    unusedFunctions: number;
    orphanedModules: number;
    deadApis: number;
    unreachableCode: number;
    total: number;
  },
  reportMarkdown: string
): string {
  const lines: string[] = [];

  lines.push("## 🔍 Dead Code Analysis Results");
  lines.push("");
  lines.push("This PR was automatically generated by **Dead Code Finder** powered by GitHub Copilot SDK.");
  lines.push("");
  lines.push("### Summary");
  lines.push("");
  lines.push(`- **${summary.unusedFunctions}** unused functions/exports`);
  lines.push(`- **${summary.orphanedModules}** orphaned modules`);
  lines.push(`- **${summary.deadApis}** dead APIs`);
  lines.push(`- **${summary.unreachableCode}** unreachable code blocks`);
  lines.push(`- **${summary.total}** total findings`);
  lines.push("");
  lines.push("### Recommended Actions");
  lines.push("");

  const highConfidence = findings.filter((f) => f.confidence === "high");
  const mediumConfidence = findings.filter((f) => f.confidence === "medium");

  if (highConfidence.length > 0) {
    lines.push(`**Safe to remove** (${highConfidence.length} items):`);
    for (const f of highConfidence) {
      lines.push(`- \`${f.symbolName}\` in \`${f.filePath}\` (line ${f.line})`);
    }
    lines.push("");
  }

  if (mediumConfidence.length > 0) {
    lines.push(`**Needs review** (${mediumConfidence.length} items):`);
    for (const f of mediumConfidence) {
      lines.push(`- \`${f.symbolName}\` in \`${f.filePath}\` (line ${f.line}) — ${f.reason}`);
    }
    lines.push("");
  }

  lines.push("<details>");
  lines.push("<summary>Full Report</summary>");
  lines.push("");
  lines.push(reportMarkdown);
  lines.push("");
  lines.push("</details>");

  return lines.join("\n");
}
