import type { DeadCodeFinding, Confidence } from "./types.js";

/**
 * Format dead code findings as a Markdown report.
 */
export function formatMarkdown(
  findings: DeadCodeFinding[],
  summary: { unusedFunctions: number; orphanedModules: number; deadApis: number; unreachableCode: number; total: number }
): string {
  const lines: string[] = [];

  lines.push("# Dead Code Report");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Category | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Unused Functions | ${summary.unusedFunctions} |`);
  lines.push(`| Orphaned Modules | ${summary.orphanedModules} |`);
  lines.push(`| Dead APIs | ${summary.deadApis} |`);
  lines.push(`| Unreachable Code | ${summary.unreachableCode} |`);
  lines.push(`| **Total** | **${summary.total}** |`);
  lines.push("");

  if (findings.length === 0) {
    lines.push("> No dead code found. Your codebase is clean!");
    return lines.join("\n");
  }

  // Group by type
  const groups: Record<string, DeadCodeFinding[]> = {
    "unused-function": [],
    "orphaned-module": [],
    "dead-api": [],
    "unreachable-code": [],
  };

  for (const f of findings) {
    groups[f.type].push(f);
  }

  const typeLabels: Record<string, string> = {
    "unused-function": "Unused Functions & Exports",
    "orphaned-module": "Orphaned Modules",
    "dead-api": "Dead APIs",
    "unreachable-code": "Unreachable Code",
  };

  for (const [type, items] of Object.entries(groups)) {
    if (items.length === 0) continue;

    lines.push(`## ${typeLabels[type]}`);
    lines.push("");

    for (const item of items) {
      const confidenceBadge = getConfidenceBadge(item.confidence);
      lines.push(`- ${confidenceBadge} **\`${item.symbolName}\`** in \`${item.filePath}\` (line ${item.line})`);
      lines.push(`  > ${item.reason}`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by [Dead Code Finder](https://github.com/dead-code-finder) powered by GitHub Copilot SDK*");

  return lines.join("\n");
}

/**
 * Format findings as JSON.
 */
export function formatJson(
  findings: DeadCodeFinding[],
  summary: { unusedFunctions: number; orphanedModules: number; deadApis: number; unreachableCode: number; total: number }
): string {
  return JSON.stringify({ summary, findings }, null, 2);
}

/**
 * Filter findings by confidence threshold.
 */
export function filterByConfidence(
  findings: DeadCodeFinding[],
  threshold: Confidence
): DeadCodeFinding[] {
  const levels: Record<Confidence, number> = { high: 3, medium: 2, low: 1 };
  const minLevel = levels[threshold];
  return findings.filter((f) => levels[f.confidence] >= minLevel);
}

function getConfidenceBadge(confidence: Confidence): string {
  switch (confidence) {
    case "high":
      return "🔴";
    case "medium":
      return "🟡";
    case "low":
      return "🟢";
  }
}
